config/routes.rb
Rails.application.routes.draw do
  resources :pgrades
  resources :myprests
  resources :prests
  resources :myevents
  resources :events
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#index'

  get 'home/todo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pgrade.rb
class Pgrade < ApplicationRecord
  belongs_to :user
  belongs_to :prest
end

app/controllers/pgrades_controller.rb
class PgradesController < ApplicationController
  before_action :set_pgrade, only: %i[ show edit update destroy ]

  # GET /pgrades or /pgrades.json
  def index
    @pgrades = Pgrade.all
  end

  # GET /pgrades/1 or /pgrades/1.json
  def show
  end

  # GET /pgrades/new
  def new
    @pgrade = Pgrade.new
  end

  # GET /pgrades/1/edit
  def edit
  end

  # POST /pgrades or /pgrades.json
  def create
    joined = Pgrade.where(prest_id: pgrade_params[:prest_id], user_id: current_user.id)
    
    if joined.present?
      redirect_to new_pgrade_path, alert: 'You have reveiwed this presenation! See Evaluations for details.'
    else
      @pgrade = Pgrade.new(pgrade_params)

      respond_to do |format|
        if @pgrade.save
          format.html { redirect_to @pgrade, notice: "Evaluation was successfully submitted." }
          format.json { render :show, status: :created, location: @pgrade }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @pgrade.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /pgrades/1 or /pgrades/1.json
  def update
    respond_to do |format|
      if @pgrade.update(pgrade_params)
        format.html { redirect_to @pgrade, notice: "Evaluation was successfully updated." }
        format.json { render :show, status: :ok, location: @pgrade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pgrade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pgrades/1 or /pgrades/1.json
  def destroy
    @pgrade.destroy
    respond_to do |format|
      format.html { redirect_to pgrades_url, notice: "Evaluation was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pgrade
      @pgrade = Pgrade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pgrade_params
      params.require(:pgrade).permit(:user_id, :prest_id, :pd_socre, :pd_review)
    end
end

app/helpers/pgrades_helper.rb
module PgradesHelper
end

app/views/pgrades/_form.html.erb
<%= form_with(model: pgrade, local: true) do |form| %>
  <% if pgrade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pgrade.errors.count, "error") %> prohibited this pgrade from being saved:</h2>

      <ul>
        <% pgrade.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :pgrade_user_id, value: current_user.id, :hidden=>true %>
  </div> 

  <% myp = [] %>
  <% Myprest.where(user_id: current_user.id).each do |p| %>
    <% myp << p.prest_id  %>
  <% end %>
  <% pres = [] %>
  <% Myevent.where(user_id: current_user.id).each do |e| %>
    <% pres.concat(Prest.where(event_id: e.event_id).ids)  %>
  <% end %> 
  <% pres -= myp %>

  <div class="mb-3">
    <%= form.label "Select Presentation:" %>
    <%= form.select(:prest_id, options_for_select(Prest.where(id: pres).collect {|p| [ p.prest_name.concat(" << ").concat(Event.find(p.event_id).evt_name), p.id ] })) %>
  </div>

  <div class="input-group mb-3">
    <%= form.label "Score", class:"input-group-text" %>
    <%= form.number_field :pd_socre, class:"form-control" %>
  </div>

  <div class="input-group mb-3">
    <%= form.label "Reviews", class:"input-group-text" %>
    <%= form.text_area :pd_review, class:"form-control", rows: 5 %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-primary", value: btn_name %>
  </div>
<% end %>

app/views/pgrades/edit.html.erb
<h1>Editing Pgrade</h1>

<%= render 'form', pgrade: @pgrade, btn_name: "Update Review" %>

app/views/pgrades/index.html.erb
<% if current_user.admin %>
  <h1>Received Evaluations</h1>
<% else %>
  <h1>My Submitted Evaluations</h1>
<% end %>

<table class="table table-primary table-sm">
  <thead>
    <tr>
      <th>Audience ID</th>
      <th>Audience Name</th>
      <th>Presentation ID</th>
      <th>Presentation Name</th>
      <th>Score</th>
      <th>Review</th>
      <th>Latest Post Date</th>
      <th>Status</th>
      <th>Events</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @pgrades.each do |pgrade| %>
      <% if Prest.all.find(pgrade.prest_id).user_id == current_user.id || pgrade.user_id == current_user.id %>
        <tr>
          <td><%= pgrade.user_id %></td>
          <% user = User.all.find(pgrade.user_id) %>
          <td><%= user.first_name.concat(" ").concat(user.last_name) %></td>
          <td><%= pgrade.prest_id %></td>
          <% pre = Prest.all.find(pgrade.prest_id) %>
          <td><%= link_to pre.prest_name, pre %></td>
          <td><%= pgrade.pd_socre %></td>
          <td><%= link_to 'details', pgrade %></td>
          <td><%= pgrade.updated_at %></td>
          <% if pre.prest_evdue < pgrade.updated_at %>
            <td><strong>Late</strong></td>
          <% else %>
            <td>Submitted</td>
          <% end %>
          <% evt = Event.all.find(pre.event_id) %>
          <td><%= link_to evt.evt_name, evt %></td>
          <% if !current_user.admin %>
            <td><%= link_to 'Edit', edit_pgrade_path(pgrade) %></td>
          <% else %>
            <td><%= link_to 'Delete', pgrade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if !current_user.admin %>
  <p>To view your presentations' feedbacks, go to <strong>My Presentations</strong> - <strong>Reviews for me</strong> section.</p>
<% end %>

app/views/pgrades/new.html.erb
<h1>Add a New Review</h1>

<%= render 'form', pgrade: @pgrade, btn_name: 'Submit' %>
<br/>
<%= link_to 'Back', pgrades_path, class:"btn btn-dark" %>

<br/><br/>
<p><Strong>Reminder:</Strong> You cannot evaluate your own presentation.</p>
<p>Do not submit same presentation review more than one time. If you want to edit your reviews, go to <Strong>'Evaluations' - 'Edit'<Strong></p>

app/views/pgrades/show.html.erb
<% user = User.all.find(@pgrade.user_id) %>
<% pre = Prest.all.find(@pgrade.prest_id) %>
<% revs = Pgrade.where(prest_id: @pgrade.prest_id)%>
<h1>Evaluation Details</h1>
<p><strong>Audience ID: </strong> <%= user.id %></p>
<p><strong>Audience Name: </strong> <%= user.first_name.concat(" ").concat(user.last_name) %></p>
<p><strong>Presentation ID: </strong><%= @pgrade.prest_id %></p>
<p><strong>Presentation Name: </strong><%= link_to pre.prest_name, pre %></p>
<% evt = Event.all.find(pre.event_id) %>
<p><strong>Event: </strong><%= link_to evt.evt_name, evt %></p>
<p><strong>Score: </strong><%= @pgrade.pd_socre %></p>
<p><strong>Review: </strong><%= @pgrade.pd_review %></p>
<p><strong>Post date: </strong><%= @pgrade.updated_at %></p>

<% if current_user.admin || Myprest.where(user_id: current_user.id, prest_id: pre.id).present? %>
<% revs = Pgrade.where(prest_id: pre.id)%>
<hr>
<p>
  <strong>Total Reviews: </strong> <%= revs.length.to_s.concat("   ") %>records |
  <strong>Total Score: </strong> <%= revs.sum(:pd_socre) %> |
  <strong>Average Score: </strong> <%= revs.average(:pd_socre) %> |
  <strong>Highest Score: </strong> <%= revs.maximum(:pd_socre) %> |
  <strong>Lowest Score: </strong> <%= revs.minimum(:pd_socre) %>
</p>
<% end %>