config/routes.rb
Rails.application.routes.draw do
  resources :pgrades
  resources :myprests
  resources :prests
  resources :myevents
  resources :events
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#index'

  get 'home/todo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def todo  
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <% if !current_user.nil? && current_user.admin %>
      <%= link_to 'ezAEP Admin', root_path, class:"navbar-brand" %>
    <% else %>
     <%= link_to 'ezAEP', root_path, class:"navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Events", events_path, class: "nav-link active" %>
          </li>
          
          <% if current_user.admin %>
            <li class="nav-item">
              <%= link_to "Presentations", prests_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Speakers", myprests_path, class: "nav-link active" %>
            </li> 
          <% else %>
            <li class="nav-item">
              <%= link_to "My Events", myevents_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "My Presentations", myprests_path, class: "nav-link active" %>
            <li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Evaluations", pgrades_path, class: "nav-link active" %>
          </li>

          <% if !current_user.admin %>
            <li class="nav-item">
              <%= link_to "TODOs", home_todo_path, class: "nav-link active" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Setting", edit_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link active" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
  <% if !current_user.nil? && current_user.admin %>
   <h1> Welcome to ezAEP Admin Dashboard! </h1>
  <% else %>
    <h1> Welcome to ezAEP Portal</h1>
  <% end %>

<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <%= image_tag("w0.jpg", height: 500,class: "d-block w-100", alt: "audience") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <%= image_tag("w1.jpg", height: 500, class: "d-block w-100", alt: "audience") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag("w2.jpg", height:500, class: "d-block w-100", alt: "audience") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<p> Powered by <%= link_to 'NicholasTec.', 'https://nicholastec.com' %> Smart Solution @2022.NTSS V2.1.12 | Webapp_version: v0.11.28 </p>
<p> Ohio-State Unniitec. Team </p>

app/views/home/todo.html.erb
<% if current_user.admin %>
  <h1>ALL Evaluations</h1>
<% else %>
  <h1>My Todo Evaluations</h1>
<% end %>

<% joined_events = [] %>
<% Myevent.where(user_id: current_user.id).each do |me| %>
    <% joined_events << me.event_id %>
<% end %>
<% joined_prest = Prest.where(event_id: joined_events).ids %>

<% speaked_prest = [] %>
<% Myprest.where(user_id: current_user.id).each do |ms| %>
    <% speaked_prest << ms.prest_id %>
<% end %>
<% speaked_prest %>

<% reviewed_prest = [] %>
<% Pgrade.where(user_id: current_user.id).each do |mr| %>
    <% reviewed_prest << mr.prest_id %>
<% end %>
<% reviewed_prest %>

<% todo_prest = joined_prest - speaked_prest - reviewed_prest %>

<table class="table table-primary table-sm">
  <thead>
    <tr>
      <th>Presentation ID</th>
      <th>Presentation Name</th>
      <th>Evaluation Due</th>
      <th>Events</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% todo_prest.each do |p| %>
        <% pre = Prest.all.find(p) %>
        <tr>
          <td><%= pre.id %></td>
          <td><%= link_to pre.prest_name, pre %></td>
          <td><%= pre.prest_evdue %></td>
          <% evt = Event.all.find(pre.event_id) %>
          <td><%= link_to evt.evt_name, evt %></td>
          <% if pre.prest_evdue < Date.today %>
            <td><strong>Past Due</strong></td>
          <% else %>
            <td>Open</td>
          <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if !current_user.admin %>
  <%= link_to 'New Evaluation', new_pgrade_path, class:"btn btn-primary" %>
<% end %>