config/routes.rb
Rails.application.routes.draw do
  resources :pgrades
  resources :myprests
  resources :prests
  resources :myevents
  resources :events
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#index'

  get 'home/todo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :myevents
  has_many :prests
  has_many :users, through: :myevents
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[]
  # before_action :correct_host, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    # @event = Event.new(event_params)
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_host
    @event = current_user.events.find_by(id: params[:id])
    redirect_to events_path, notice: "Not Authorized!" if @event.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:evt_name, :evt_host, :evt_sdate, :evt_edate, :evt_desc, :evt_public, :evt_code, :user_id, user_ids: [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.label "Event Title", class:"input-group-text" %>
    <%= form.text_field :evt_name, class:"form-control" %>
  </div>

  <div class="input-group mb-3">
    <%= form.label "Event Host", class:"input-group-text" %>
    <%= form.text_field :evt_host, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label "Start date", class:"form-label" %>
    <%= form.date_select :evt_sdate %>
  </div>

  <div class="mb-3">
    <%= form.label "End date", class:"form-label" %>
    <%= form.date_select :evt_edate %>
  </div>

  <div class="input-group">
    <%= form.label "Description", class:"input-group-text" %>
    <%= form.text_area :evt_desc, class:"form-control", rows: 5 %>
  </div>
  <div class="mb-3">

  </div>

  <div class="form-check">
    <%= form.radio_button :evt_public, false, autofocus: true, class:"form-check-input" %>
    <%= form.label :event, "Private Event (Join via Access code provided by you)", class:"form-check-label" %><br />
    <%= form.radio_button :evt_public, true, class:"form-check-input" %>
    <%= form.label :evt_public, "Public Event (Access code is visible by all publics)", class:"form-check-label" %><br />
  </div>
  
  <div class="input-group mb-3">
    <% v = (0...8).map { ('a'..'z').to_a[rand(26)] }.join %>
    <%= form.label "Access Code", class:"input-group-text" %>
    <%= form.text_field :evt_code, value: v, :readonly=>true, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :event_user_id, value: current_user.id, :hidden=>true %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>
<br/>
<%= link_to 'Back', @event, class:"btn btn-dark" %>

app/views/events/index.html.erb
<% if current_user.admin %>
  <h1>My Published Events</h1>
<% else %>
  <h1>Public Events - Free to JOIN! </h1>
<% end %>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th>Event ID</th>
      <th>Event Name</th>
      <th>Host</th>
      <th>Start Date</th>
      <th>Public</th>
      <th>Creator</th>
      <th>Access Code</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
    <% if current_user == event.user || !current_user.admin && event.evt_public %>
      <tr>
        <td><%= event.id %></td>
        <td><%= link_to event.evt_name, event %></td>
        <td><%= event.evt_host %></td>
        <td><%= event.evt_sdate %></td>
        <td><%= event.evt_public %></td>
        <% @creator = User.find(event.user_id) %>
        <td><%= @creator.first_name %> <%= @creator.last_name %></td>
        <td><%= event.evt_code %></td>
        <% if current_user.admin %>
        <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Delete current event? ' } %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin %>
  <%= link_to 'New Event', new_event_path, class: "btn btn-primary" %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>
<br/>
<%= link_to 'Back', events_path, class:"btn btn-dark" %>

app/views/events/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @event.evt_name %></h1>
  <p class="lead">
    <% if @event.evt_public %>
      <strong>Public Event</strong>
    <% else %>
      <strong>Private Event</strong>
    <% end %>  |
    <strong>Host:</strong> <%= @event.evt_host %> | 
    <strong>Start date:</strong> <%= @event.evt_sdate %> | 
    <strong>End date:</strong> <%= @event.evt_edate %> |
    <strong>Creator:</strong>
    <% @creator = User.find(@event.user_id) %>
    <%= @creator.first_name %>
    <%= @creator.last_name %> |
    <strong>Code:</strong>
    <%= @event.evt_code %>
  </p>
  <hr class="my-4">
  <%= @event.evt_desc %>
</div>

<br/>

<% if current_user.admin %>
  <%= link_to '<< Events', events_path, class: "btn btn-primary" %>
  <%= link_to 'Edit Event', edit_event_path(@event), class: "btn btn-dark" %> 
  <br/><br/>
<% end %>

<hr>
<h2>Presentations List</h2>
<table class="table table-striped"> 
  <thead class="table-dark">
    <tr>
      <th>Presentation Name</th>
      <th>Evaluation Due</th>
      <th>Event Name</th>
      <% if current_user.admin %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% Prest.all.each do |prest| %>
      <% if prest.event_id == @event.id %>
      <tr>
        <td><%= link_to prest.prest_name, prest %></td>
        <td><%= prest.prest_evdue %></td>
        <td><%= Event.all.find(prest.event_id).evt_name %></td>
        <% if current_user.admin %>
          <td><%= link_to 'Delete', prest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br/>

<% if current_user.admin %>
  <%= link_to 'New Presentation', new_prest_path, class:"btn btn-success" %>
  <br/><br/>

  <hr>
  <h2>Enrolled People</h2>
  <table class="table table-success table-striped table-sm">
    <thead>
      <tr>
        <th>Participant ID</th>
        <th>Participant Name</th>
        <th>Joining Date</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% enrolled_num = 0 %>
      <% Myevent.all.each do |myevent| %>
        <% if current_user == @event.user && myevent.event_id == @event.id %>
          <% enrolled_num += 1 %>
          <tr>
            <td><%= myevent.user_id %></td>
            <% @person = User.find(myevent.user_id) %>
            <td><%= @person.first_name %> <%= @person.last_name %></td>
            <td><%= myevent.created_at %></td>
            <td><%= link_to 'Remove', myevent, method: :delete, data: { confirm: 'Remove the person from current event?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>
<p>There are total <Strong><%= enrolled_num %></Strong> people attended this event.</p>
<br/>