config/routes.rb
Rails.application.routes.draw do
  resources :pgrades
  resources :myprests
  resources :prests
  resources :myevents
  resources :events
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#index'

  get 'home/todo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/prest.rb
class Prest < ApplicationRecord
  belongs_to :event
  has_many :users, through: :myprests
  has_many :users, through: :pgrades
end

app/controllers/prests_controller.rb
class PrestsController < ApplicationController
  before_action :set_prest, only: %i[ show edit update destroy ]

  # GET /prests or /prests.json
  def index
    @prests = Prest.all
  end

  # GET /prests/1 or /prests/1.json
  def show
  end

  # GET /prests/new
  def new
    @prest = Prest.new
  end

  # GET /prests/1/edit
  def edit
  end

  # POST /prests or /prests.json
  def create
    @prest = Prest.new(prest_params)

    respond_to do |format|
      if @prest.save
        format.html { redirect_to @prest, notice: "The presentation was successfully created!" }
        format.json { render :show, status: :created, location: @prest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prests/1 or /prests/1.json
  def update
    respond_to do |format|
      if @prest.update(prest_params)
        format.html { redirect_to @prest, notice: "The presentation was successfully updated!" }
        format.json { render :show, status: :ok, location: @prest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prests/1 or /prests/1.json
  def destroy
    @prest.destroy
    respond_to do |format|
      format.html { redirect_to prests_url, notice: "The presentation was successfully deleted!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prest
      @prest = Prest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prest_params
      params.require(:prest).permit(:prest_name, :prest_evdue, :prest_desc, :event_id, :user_id)
    end
end

app/helpers/prests_helper.rb
module PrestsHelper
end

app/views/prests/_form.html.erb
<%= form_with(model: prest, local: true) do |form| %>
  <% if prest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prest.errors.count, "error") %> prohibited this prest from being saved:</h2>

      <ul>
        <% prest.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.label "Title", class:"input-group-text" %>
    <%= form.text_field :prest_name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label "Evaluation Due" %>
    <%= form.date_select :prest_evdue %>
  </div>

  <div class="input-group mb-3">
    <%= form.label "Description", class:"input-group-text" %>
    <%= form.text_area :prest_desc, class:"form-control", rows: 5 %>
  </div>

  <div class="mb-3">
    <%= form.label "Choose your event" %>
    <%= form.select(:event_id, options_for_select(Event.where(user_id: current_user.id).collect {|e| [ e.evt_name, e.id.to_i ] })) %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :prest_user_id, value: current_user.id, :hidden=>true %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-primary", value: btn_name %>
  </div>
<% end %>

app/views/prests/edit.html.erb
<h1>Editing Presentation</h1>

<%= render 'form', prest: @prest, btn_name: 'Update Presentation' %>

<br/>
<%= link_to 'Back', @prest, class:"btn btn-dark" %>

app/views/prests/index.html.erb
<h1>Presentations</h1>

<table class="table table-striped table-sm"> 
  <thead class="table-primary">
    <tr>
      <th>Presentation Name</th>
      <th>Avg Score</th>
      <th>Evaluation Due</th>
      <th>Event Name</th>
      <th>Creator</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @prests.each do |prest| %>

      <% if current_user.admin && prest.user_id == current_user.id %>
      <tr>
        <td><%= link_to prest.prest_name, prest %></td>
        <% revs = Pgrade.where(prest_id: prest.id)%>
        <td><%= revs.average(:pd_socre) %></td>
        <td><%= prest.prest_evdue %></td>
        <td><%= Event.all.find(prest.event_id).evt_name %></td>
        <td>
          <%= User.all.find(prest.user_id).first_name %>
          <%= User.all.find(prest.user_id).last_name %>
        </td>
        <td><%= link_to 'Delete', prest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presentation', new_prest_path, class:"btn btn-success" %>

app/views/prests/new.html.erb
<h1>New Presentation</h1>

<%= render 'form', prest: @prest, btn_name:"Create" %>

app/views/prests/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @prest.prest_name %></h1>
  <p class="lead">
    <strong>Presentation</strong> |
    <strong>ID:</strong> <%= @prest.id %> | 
    <strong>Event:</strong>  <%= Event.all.find(@prest.event_id).evt_name %> |
    <strong>Evaluation Due:</strong> <%= @prest.prest_evdue %>  |
    <strong>Creator:</strong>    
    <%= User.all.find(@prest.user_id).first_name %>
    <%= User.all.find(@prest.user_id).last_name %>
  </p>
  <hr class="my-4">
  <p> <%= @prest.prest_desc %> </p>
  <br/>
</div>

<% if current_user.admin %>
  <%= link_to '<< Current Event', Event.all.find(@prest.event_id), class: "btn btn-primary" %> 
  <%= link_to 'Edit Presentation', edit_prest_path(@prest), class: "btn btn-dark" %>
  <%= link_to 'Delete', @prest, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%>
  <br/><br/>
<% end %>

<hr>
<h2>Speakers</h2>

<table class="table table-striped">
  <thead class="table-secondary">
    <tr>
      <th>Speaker ID</th>
      <th>Speaker Name</th>
      <th>Contact Email</th>
      <th>Presentation ID</th>
      <th>Presentation Name</th>
      <th>Event</th>
      <% if current_user.admin %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% Myprest.all.each do |myprest| %>
      <% correct_admin = current_user.admin && Prest.all.find(myprest.prest_id).user_id == current_user.id %>
      <% correct_user = !current_user.admin %>
      <% if (correct_admin || correct_user) && myprest.prest_id == @prest.id %>
        <tr>
          <td><%= myprest.user_id %></td>
          <td>
            <%= User.all.find(myprest.user_id).first_name %>
            <%= User.all.find(myprest.user_id).last_name %>
          </td>
          <td><%= User.all.find(myprest.user_id).email %></td>
          <td><%= myprest.prest_id %></td>
          <% p = Prest.all.find(myprest.prest_id) %>
          <td><%= p.prest_name %></td>
          <td><%= Event.all.find(p.event_id).evt_name %></td>
          <% if current_user.admin %>
            <td><%= link_to 'Remove', myprest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br/>

<% if current_user.admin %>
  <%= link_to 'New Speaker', new_myprest_path, class:"btn btn-info" %>
  <br/><br/>
<% end %>
<hr/>


<% if current_user.admin %>
  <h2>ALL Reviews</h2>
<% elsif Myprest.where(user_id: current_user.id, prest_id: @prest.id).present? %>
  <h2>Reviews for me</h2>
  <p>Only you and your team could see all presentation reviews from the audience.</p>
<% else %>
  <h2>My Post Reviews</h2>
  <p>You could only see your own review to this presentation, if no record shown, please post your review before evaluation due date <%= @prest.prest_evdue %>.</p>
<% end %>

<% if current_user.admin || Myprest.where(user_id: current_user.id, prest_id: @prest.id).present? %>
<% revs = Pgrade.where(prest_id: @prest.id)%>
<p>
  <strong>Total Reviews: </strong> <%= revs.length.to_s.concat("   ") %>records |
  <strong>Total Score: </strong> <%= revs.sum(:pd_socre) %> |
  <strong>Average Score: </strong> <%= revs.average(:pd_socre) %> |
  <strong>Highest Score: </strong> <%= revs.maximum(:pd_socre) %> |
  <strong>Lowest Score: </strong> <%= revs.minimum(:pd_socre) %>
</p>
<% end %>

  <table class="table table-primary table-sm">
    <thead>
        <tr>
          <th>Audience ID</th>
          <th>Audience Name</th>
          <th>Presentation ID</th>
          <th>Presentation Name</th>
          <th>Score</th>
          <th>Review</th>
          <th>Post Date</th>
          <% if current_user.admin %>
            <th colspan="1"></th>
          <% end %>
        </tr>
      </thead>

    <tbody>
      <% Pgrade.all.each do |pgrade| %>
        <!-- If admin created this presentation -->
        <% correct_one = Prest.all.find(pgrade.prest_id).user_id == current_user.id %>
        <!-- If audience post a review on this presentation -->
        <% correct_two = pgrade.user_id == current_user.id %>
        <!-- If speaker attended this presentation -->
        <% correct_three = Myprest.where(user_id: current_user.id, prest_id: pgrade.prest_id).present? %>

        <% if  (correct_one || correct_two || correct_three) && pgrade.prest_id == @prest.id %>
          <tr>
            <td><%= pgrade.user_id %></td>
            <% user = User.all.find(pgrade.user_id) %>
            <td><%= user.first_name.concat(" ").concat(user.last_name) %></td>
            <td><%= pgrade.prest_id %></td>
            <td><%= Prest.all.find(pgrade.prest_id).prest_name %></td>
            <td><%= pgrade.pd_socre %></td>
            <td><%= link_to 'details', pgrade %></td>
            <td><%= pgrade.updated_at %></td>
            <% if current_user.admin %>
              <td><%= link_to 'Delete', pgrade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>